name: Trigger auto deployment

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      - master
      - develop
    paths:
      - '**'
      - '.github/workflows/deployment.yml'

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test

  build-image:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: crtestinggeneral.azurecr.io
          username: ${{ secrets.CASRVYMKRSERVERDEV_REGISTRY_USERNAME }}
          password: ${{ secrets.CASRVYMKRSERVERDEV_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: crtestinggeneral.azurecr.io/srvymkr-server:latest
          file: ./Dockerfile
          context: ./

  deploy-dev:
    runs-on: ubuntu-latest
    needs:
      - test
      - build-image

    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CASRVYMKRSERVERDEV_AZURE_CREDENTIALS }}

      # az containerapp revision restart - is needed when new image has the same tag
      # (currently tag is always set to be "latest")
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ca-srvymkr-server-dev -g rg-personal-test-general --server crtestinggeneral.azurecr.io --username  ${{ secrets.CASRVYMKRSERVERDEV_REGISTRY_USERNAME }} --password ${{ secrets.CASRVYMKRSERVERDEV_REGISTRY_PASSWORD }}
            az containerapp update -n ca-srvymkr-server-dev -g rg-personal-test-general --image crtestinggeneral.azurecr.io/srvymkr-server:latest
            az containerapp revision restart --revision "ca-srvymkr-server-dev--revdev" --resource-group "rg-personal-test-general"

  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - test
      - build-image

    if: github.ref == 'refs/heads/master'
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CASRVYMKRSERVERPROD_AZURE_CREDENTIALS }}

      # az containerapp revision restart - is needed when new image has the same tag
      # (currently tag is always set to be "latest")
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ca-srvymkr-server-prod -g rg-personal-test-general --server crtestinggeneral.azurecr.io --username  ${{ secrets.CASRVYMKRSERVERPROD_REGISTRY_USERNAME }} --password ${{ secrets.CASRVYMKRSERVERPROD_REGISTRY_PASSWORD }}
            az containerapp update -n ca-srvymkr-server-prod -g rg-personal-test-general --image crtestinggeneral.azurecr.io/srvymkr-server:latest
            az containerapp revision restart --revision "ca-srvymkr-server-prod--revprod" --resource-group "rg-personal-test-general"
