name: Infrastructure Manual Deployment

# When this action will be executed
on:
  # Allow mannually trigger
  workflow_dispatch:

env:
  RESOURCE_GROUP_NAME: 'srvymkr-training-rg'
  REGION_LOCATION_NAME: 'westeurope'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  preview-infrastructure:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout your repository under $GITHUB_WORKSPACE, so your job can access it 
      - uses: actions/checkout@v3
      
      # IF THIS IS NOT DONE UNTIL NOW:
      # az ad sp create-for-rbac --name srvymkr-github-contributor-sp --role contributor --scope /subscriptions/$SUBSCRIPTION_ID --sdk-auth
      # Result goes to: SRVYMKR_AZURE_SP_CREDENTIALS
      # Result tennandId goes to: params.json
      # az ad sp list o -table
      # Result appId, objId goes to: params.json
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SRVYMKR_AZURE_SP_CREDENTIALS }}
      
      # Deleting the RG will mark the Key Vault as Deleted but not delete it. Purge it with this command:
      #   az keyvault purge --name srvymkr-key-vault 
      - name: Purge Old Key Vault
        continue-on-error: true
        uses: Azure/cli@v1.0.6
        with:
          inlineScript: | 
            az keyvault purge --name srvymkr-key-vault

      # If the Resource Group exists before this script gets executed it will throw an error
      # Execute a script to delete the resource group (alongside with all resources in it)
      # The Bicep will recreate those resources later.
      #   az group delete --name srvymkr-training-rg
      - name: Create Resource Group
        continue-on-error: true
        uses: Azure/cli@v1.0.6
        with:
          inlineScript: | 
            az group create --name $RESOURCE_GROUP_NAME --location $REGION_LOCATION_NAME 

      - name: Preview Infrastructure Changes
        uses: Azure/deployment-what-if-action@v1.0.0
        with:
          subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroup: $RESOURCE_GROUP_NAME
          templateFile: ./infrastructure/bicep/main.bicep
          parametersFile: ./infrastructure/bicep/params.json

  deploy-infrastructure:
    needs: [preview-infrastructure]
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository under $GITHUB_WORKSPACE, so your job can access it 
      - uses: actions/checkout@v3
      
      # IF THIS IS NOT DONE UNTIL NOW:
      # az ad sp create-for-rbac --name srvymkr-github-contributor-sp --role contributor --scope /subscriptions/$SUBSCRIPTION_ID --sdk-auth
      # Result goes to: SRVYMKR_AZURE_SP_CREDENTIALS
      # Result tennandId goes to: params.json
      # az ad sp list o -table
      # Result appId, objId goes toÑ params.json
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SRVYMKR_AZURE_SP_CREDENTIALS }}
      
      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: srvymkr-training-rg
          template: ./infrastructure/bicep/main.bicep
          parameters: ./infrastructure/bicep/params.json
          failOnStdErr: false