name: Trigger auto deployment

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  # push:
  #   branches:
  #     - master
  #     - develop
  #   paths:
  #     - '**'
  #     - '.github/workflows/server-deployment.yml'

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test

  build-image:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: srvymkracr.azurecr.io
          username: ${{ secrets.AZURE_SP_CLIENT_ID }}
          password: ${{ secrets.AZURE_SP_CLIENT_SECRET }}
      
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: srvymkracr.azurecr.io/srvymkr-server-image:latest
          file: ./Dockerfile
          context: ./

  deploy-dev:
    runs-on: ubuntu-latest
    needs:
      - test
      - build-image

    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SRVYMKR_AZURE_SP_CREDENTIALS }}

      # az containerapp revision restart - is needed when new image has the same tag
      # (currently tag is always set to be "latest")
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n srvymkr-server-dev-ca -g srvymkr-training-rg --server srvymkracr.azurecr.io --username  ${{ secrets.AZURE_SP_CLIENT_ID }} --password ${{ secrets.AZURE_SP_CLIENT_SECRET }}
            az containerapp update -n srvymkr-server-dev-ca -g srvymkr-training-rg --image srvymkracr.azurecr.io/srvymkr-server-image:latest --revision-suffix revision
            az containerapp revision restart --revision "srvymkr-server-dev-ca--revision" --resource-group "srvymkr-training-rg"

  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - test
      - build-image

    if: github.ref == 'refs/heads/master'
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SRVYMKR_AZURE_SP_CREDENTIALS }}

      # az containerapp revision restart - is needed when new image has the same tag
      # (currently tag is always set to be "latest")
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n srvymkr-server-prod-ca -g srvymkr-training-rg --server srvymkracr.azurecr.io --username  ${{ secrets.AZURE_SP_CLIENT_ID }} --password ${{ secrets.AZURE_SP_CLIENT_SECRET }}
            az containerapp update -n srvymkr-server-prod-ca -g srvymkr-training-rg --image srvymkracr.azurecr.io/srvymkr-server-image:latest --revision-suffix revision
            az containerapp revision restart --revision "srvymkr-server-prod-ca--revision" --resource-group "srvymkr-training-rg"
